# SwiftLint Configuration for Kickback iOS App
# Enforces clean, consistent Swift code following orchestrator requirements

# Directories to analyze
included:
  - KickbackApp
  - KickbackAppTests
  - KickbackAppUITests

# Directories to ignore
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - KickbackApp.xcodeproj
  - KickbackApp.xcworkspace

# Disabled rules (rules we don't want to enforce)
disabled_rules:
  - todo # Allow TODO comments for development
  - line_length # We'll handle this with opt_in_rules instead
  - trailing_whitespace # Let swift-format handle this

# Opt-in rules (rules that aren't enabled by default)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 5
  error: 7

type_body_length:
  warning: 300
  error: 400

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - Row
    - Tag
    - Key
    - URL
    - ID

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - to
    - at
    - on
    - in

# Nesting configuration
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Force unwrapping configuration
force_unwrapping:
  severity: error

# Force cast configuration
force_cast:
  severity: error

# Empty count configuration
empty_count:
  severity: error

# File header configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  KickbackApp
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/

# Large tuple configuration
large_tuple:
  warning: 3
  error: 4

# Cyclomatic complexity configuration
cyclomatic_complexity:
  warning: 10
  error: 15

# Custom rules for Kickback-specific requirements
custom_rules:
  no_emojis_in_code:
    name: "No Emojis in Code"
    regex: '[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]'
    message: "Emojis are not allowed in code per project requirements. UI must be emoji-free."
    severity: error

  no_network_calls:
    name: "No Network Calls"
    regex: 'URLSession|NSURLConnection|Alamofire|AFNetworking|fetch|XMLHttpRequest'
    message: "Network calls are forbidden per offline-first mandate. All processing must be on-device."
    severity: error

  require_doc_comments_public:
    name: "Public Symbols Require Documentation"
    regex: '^[ ]*public (?:class|struct|enum|protocol|func|var|let)(?!.*\/\/\/)'
    message: "All public symbols require documentation comments (///) per orchestrator requirements."
    severity: warning

  prefer_async_await:
    name: "Prefer async/await over completion handlers"
    regex: 'completion:.*@escaping.*->.*Void'
    message: "Prefer async/await over completion handlers for new code."
    severity: warning

  no_hardcoded_strings:
    name: "No Hardcoded User-Facing Strings"
    regex: 'Text\("(?!.*\{.*\}).*[a-zA-Z].*"\)'
    message: "User-facing strings should be localized or use string interpolation for dynamic content."
    severity: warning

# Reporter configuration
reporter: "xcode"

# SwiftLint version requirement
swiftlint_version: "0.50.0"